MyShoeShopGui/MyShoeShop.Web/Models/Shoe.cs
// <copyright file="Shoe.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace MyShoeShop.Web.Models
{
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// shoe.
    /// </summary>
    public class Shoe
    {
        /// <summary>
        /// Gets or sets shoe_id.
        /// </summary>
        [Display(Name = "Shoe id")]
        [Required]
        public int Shoeid { get; set; }

        /// <summary>
        /// Gets or sets name.
        /// </summary>
        [Display(Name = "Name")]
        [Required]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets size.
        /// </summary>
        [Display(Name = "Size")]
        [Required]
        public int Size { get; set; }

        /// <summary>
        /// Gets or sets type.
        /// </summary>
        [Display(Name = "Type")]
        [Required]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets color.
        /// </summary>
        [Display(Name = "Color")]
        [Required]
        public string Color { get; set; }

        /// <summary>
        /// Gets or sets price.
        /// </summary>
        [Display(Name = "Price")]
        public int Price { get; set; }

        /// <summary>
        /// Gets or sets supplier_id.
        /// </summary>
        [Display(Name = "Supplier id")]
        [Required]
        public int Supplierid { get; set; }
    }
}

MyShoeShopGui/MyShoeShop.Web/Controllers/ShoesController.cs
// <copyright file="ShoesController.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace MyShoeShop.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using AutoMapper;
    using Microsoft.AspNetCore.Mvc;
    using MyShoeShop.Logic;
    using MyShoeShop.Web.Models;

    /// <summary>
    /// ShoesController.
    /// </summary>
    public class ShoesController : Controller
    {
        private ShoeLogic logic;
        private IMapper mapper;
        private ShoeListViewModel model;

        /// <summary>
        /// Initializes a new instance of the <see cref="ShoesController"/> class.
        /// </summary>
        /// <param name="logic">ShoeLogic.</param>
        /// <param name="mapper">IMapper.</param>
        public ShoesController(ShoeLogic logic, IMapper mapper)
        {
            this.logic = logic;
            this.mapper = mapper;

            this.model = new ShoeListViewModel();
            this.model.EditedShoe = new Models.Shoe();

            var shoe = logic.ReadAllCipo();
            this.model.Shoes = mapper.Map<IList<Data.Models.Cipo>, List<Models.Shoe>>(shoe);
        }

        /// <summary>
        /// Index.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Index()
        {
            this.ViewData["editAction"] = "AddNew";
            return this.View("ShoesIndex", this.model);
        }

        /// <summary>
        /// Details.
        /// </summary>
        /// <param name="id">int.</param>
        /// <returns>ActionResult.</returns>
        public ActionResult Details(int id)
        {
            return this.View("ShoesDetails", this.GetShoeModel(id));
        }

        /// <summary>
        /// Remove.
        /// </summary>
        /// <param name="id">int.</param>
        /// <returns>ActionResult.</returns>
        public ActionResult Remove(int id)
        {
            this.TempData["editResult"] = "Delete FAIL";
            this.logic.DeleteCipo(id);
            this.TempData["editResult"] = "Delete OK";
            return this.RedirectToAction(nameof(this.Index));
        }

        /// <summary>
        /// Edit.
        /// </summary>
        /// <param name="id">int.</param>
        /// <returns>ActionResult.</returns>
        public ActionResult Edit(int id)
        {
            this.ViewData["editAction"] = "Edit";
            this.model.EditedShoe = this.GetShoeModel(id);
            return this.View("ShoesIndex", this.model);
        }

        /// <summary>
        /// Edit.
        /// </summary>
        /// <param name="shoe">Shoe.</param>
        /// <param name="editAction">string.</param>
        /// <returns>ActionResult.</returns>
        [HttpPost]
        public ActionResult Edit(Models.Shoe shoe, string editAction)
        {
            if (this.ModelState.IsValid && shoe != null)
            {
                this.TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    try
                    {
                        Data.Models.Cipo cipo = new Data.Models.Cipo() { CipoId = shoe.Shoeid, Nev = shoe.Name, Meret = shoe.Size, Fajta = shoe.Type, Szin = shoe.Color, Ar = shoe.Price, BeszallitoId = shoe.Supplierid };
                        this.logic.CreateCipo(cipo);
                    }
                    catch (ArgumentException ex)
                    {
                        this.TempData["editResult"] = "Insert FAIL: " + ex.Message;
                    }
                }
                else
                {
                    Data.Models.Cipo cipo = new Data.Models.Cipo() { CipoId = shoe.Shoeid, Nev = shoe.Name, Meret = shoe.Size, Fajta = shoe.Type, Szin = shoe.Color, Ar = shoe.Price, BeszallitoId = shoe.Supplierid };
                    this.logic.UpdateCipo(shoe.Shoeid, cipo);
                }

                return this.RedirectToAction(nameof(this.Index));
            }
            else
            {
                this.ViewData["editAction"] = "Edit";
                this.model.EditedShoe = shoe;
                return this.View("ShoesIndex", this.model);
            }
        }

        private Models.Shoe GetShoeModel(int id)
        {
            Data.Models.Cipo oneShoe = this.logic.ReadCipo(id);
            return this.mapper.Map<Data.Models.Cipo, Models.Shoe>(oneShoe);
        }
    }
}

MyShoeShopGui/MyShoeShop.Web/Views/Shoes/ShoesDetails.cshtml
@model MyShoeShop.Web.Models.Shoe

@{
    ViewData["Title"] = "ShoesDetails";
}

<h2>Datasheet of one shoe</h2>

@Html.ActionLink("Back to the list", "Index")

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.Shoeid)</td>
        <td>@Html.DisplayFor(m => m.Shoeid)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Name)</td>
        <td>@Html.DisplayFor(m => m.Name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Size)</td>
        <td>@Html.DisplayFor(m => m.Size)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Price)</td>
        <td>@Html.DisplayFor(m => m.Price)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Type)</td>
        <td>@Html.DisplayFor(m => m.Type)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Color)</td>
        <td>@Html.DisplayFor(m => m.Color)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Supplierid)</td>
        <td>@Html.DisplayFor(m => m.Supplierid)</td>
    </tr>

MyShoeShopGui/MyShoeShop.Web/Views/Shoes/ShoesEdit.cshtml
@model MyShoeShop.Web.Models.Shoe

<h2>ShoesEdit</h2>

@using (Html.BeginForm("Edit", "Shoes"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.Hidden("editAction", ViewData["editAction"].ToString());


    <div class="editor-label">@Html.LabelFor(m => m.Shoeid)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Shoeid)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Size)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Size)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Price)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Price)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Type)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Type)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Color)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Color)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Supplierid)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Supplierid)</div>

    <input type="submit" value="SEND" />
}

MyShoeShopGui/MyShoeShop.Web/Views/Shoes/ShoesIndex.cshtml
@model MyShoeShop.Web.Models.ShoeListViewModel

@{
    ViewData["Title"] = "Crud Index";
}

<h2>Shoes Index</h2>

<p style="color:red">
    @TempData["editResult"]
</p>

@await Html.PartialAsync("ShoesEdit", Model.EditedShoe)

@await Html.PartialAsync("ShoesList", Model.Shoes)

MyShoeShopGui/MyShoeShop.Web/Views/Shoes/ShoesList.cshtml
@model IEnumerable<MyShoeShop.Web.Models.Shoe>

<h2>ShoesList</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database!!!</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.Shoeid)</th>
            <th>@Html.DisplayNameFor(m => m.First().Name)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => item.Shoeid)</td>
                <td>@Html.DisplayFor(m => item.Name)</td>
                <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.Shoeid })</td>
                <td>@Html.ActionLink("[DEL]", "Remove", new { id = item.Shoeid })</td>
                <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.Shoeid })</td>
            </tr>
        }
    </table>
}